version: "3.8"
name: back-end

services:
  localstack:
    image: localstack/localstack:3.3.0
    ports:
      - "4507:4507"
    environment:
      - DEBUG=1
      - GATEWAY_LISTEN=0.0.0.0:4507
    volumes:
      - "${DOCKER_SOCK_PATH:-/var/run/docker.sock}:/var/run/docker.sock"

  deployment:
    build:
      context: localstack
      args:
        BASE_NODE_IMAGE: node:20
    depends_on:
      - localstack
    volumes:
      - ./../..:/app/monorepo